package enums;

public enum ConfigProperties {
	
	URL,
	TENANTNAME,
	USERNAME,
	PASSWORD,
	ACCESSKEY,
	OVERRIDEREPORTS,
	PASSEDSTEPSSCREENSHOTS,
	FAILEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS,
	RUNMODE,
	SENDRESULTTOELK,
	SELENIUMGRIDURL,
	ELASTICURL,
	BROWSER,
	LAMBDAURL,
	BROWSERSTACKURL,
	PROJECT,
	SELENIUMVERSION,
	EMAILTESTREPORT,
	PLATFORMNAME,
	BROWSERVERSION,
	/*Datbase & Metabase conig*/
	DB_SERVERNAME,
    DB_NAME,
    DB_ENCRYPT,
    DB_TRUSTSERVERCERTIFICATE,
    DB_INTEGRATEDSECURITY,
    JDBC_DRIVERCLASS,
    JAVA_LIBRARYPATH,
	SENDRESULTTOMETABASE
	
}

