version: '3'

services:

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - 8081:8081
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:3.11.0-californium
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1200
      - SCREEN_HEIGHT=675
    ports:
      - 4444:4444
      - 5900:5900

  HubService:
    image: selenium/hub:4.0.0-rc-2-20210930
    container_name: seleniumHub
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"

  ChromeService:
    image: selenium/node-chrome:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5901:5900"
      - "7901:7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    depends_on:
      - HubService
